version: "3.8"
services:
  security_question_api:
    image: elleined/security-question-api:latest
    container_name: security_question_api
    env_file:
      - .env
    ports:
      - "8087:8087"
    networks:
      - sqa_network
    depends_on:
      mysql_server:
        condition: service_healthy

  mysql_server:
    image: mysql:8.0.32
    container_name: mysql_server
    env_file:
      - mysql.env
    ports:
      - "3307:3306"
    healthcheck:
      test: mysqladmin ping -h localhost -u root --password=$$MYSQL_ROOT_PASSWORD
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 300s
    networks:
      - sqa_network
      -
networks:
  sqa_network:
    name: sqa_network
    external: false
    ipam:
      driver: default

