version: "3.8"
services:
  sqa_app:
    build: .
    image: elleined/sqa
    container_name: sqa_app
    restart: always
    ports:
      - "8087:8087"
    environment:
      - MYSQL_HOST=mysql_server
      - MYSQL_PORT=3306
      - MYSQL_DB=sqa_db
      - MYSQL_USER=root
      - MYSQL_PASS=root
      - PORT=8087
    networks:
      - sqa_network
    depends_on:
      mysql_server:
        condition: service_healthy
  mysql_server:
    image: mysql:8.0.32
    container_name: mysql_server
    restart: always
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sqa_db
    healthcheck:
      test: mysqladmin ping -h localhost -u root --password=$$MYSQL_ROOT_PASSWORD
    networks:
      - sqa_network
networks:
  sqa_network:
    name: sqa_network
    external: false
    ipam:
      driver: default

